# 整合nacos，如果不想用nacos，可以把/nacos目录下的配置文件拷贝到/resources目录下替换使用
spring:
  config:
    import:
      - optional:nacos:config.yml
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 2822796f-fbc2-455c-b649-1da4ed87b81d
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 2822796f-fbc2-455c-b649-1da4ed87b81d