spring:
  profiles:
    active: dev
  application:
    name: mall-gateway

management:
  server:
    add-application-context-header: false
  metrics:
    export:
      prometheus:
        enabled: true
      jmx:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true

