# 整合nacos，如果不想用nacos，可以把/nacos目录下的配置文件拷贝到/resources目录下替换使用
spring:
  config:
    import:
      - optional:nacos:coupon_config.yml
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: e67a68d9-0db1-4699-8dd2-522e9022ac45
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: e67a68d9-0db1-4699-8dd2-522e9022ac45

